## 00. Pytorch Fundamentals

Research notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
print("Hellow, I'm excited to learn Pytorch!")

Hellow, I'm excited to learn Pytorch!


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0.post302


In [3]:
!nvidia-smi

Wed Jun 26 20:26:10 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.01    Driver Version: 512.78       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   51C    P8    14W /  N/A |    967MiB /  6144MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust thos random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
# Create a ranodm tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1567, 0.9655, 0.2022, 0.8815],
        [0.7915, 0.3166, 0.3798, 0.3110],
        [0.4050, 0.2104, 0.1055, 0.0977]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(
    size=(224, 224, 3)
)  # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big erros you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,  # What datatype is tensor?float, int and precision
    device=None,  # cpu or gpu
    requires_grad=False,
)  # Track the gradients with this tensors operations

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [30]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8587, 0.4386, 0.2228, 0.1589],
        [0.7952, 0.6512, 0.0333, 0.7209],
        [0.7089, 0.3621, 0.8353, 0.2549]])

In [31]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8587, 0.4386, 0.2228, 0.1589],
        [0.7952, 0.6512, 0.0333, 0.7209],
        [0.7089, 0.3621, 0.8353, 0.2549]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Substration
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [32]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [33]:
# Multuiple tensor by 10
tensor * 10

tensor([10, 20, 30])

In [34]:
tensor - 10

tensor([-9, -8, -7])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication

There are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimension** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* THIS IS BASIC MULTIPLICATION
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`


In [35]:
# Element wise multiplication
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [36]:
# Matrix multiplication (dot product)
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
%%time
value =0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.64 ms, sys: 213 µs, total: 1.86 ms
Wall time: 1.97 ms


In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 449 µs, sys: 0 ns, total: 449 µs
Wall time: 392 µs


tensor(14)

### One of the most common errors in deep learning: shape errors



In [39]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.3150, 0.4980, 0.7804],
        [0.6036, 0.2941, 0.4240],
        [0.3420, 0.2302, 0.3433]])

In [40]:
# Shapes for matrix multiplcation
tensorA = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensorB = torch.tensor([[7, 10], [8, 11], [9, 12]])
# torch.mm(tensorA, tensorB) # torch.mm is same as torch.matmul

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.

A transpose switches the axes or dimensions of a given tensor.


In [41]:
tensorB, tensorB.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [42]:
tensorB.T, tensorB.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [43]:
# The matrix multiplicatio operation works when tensorB is tansposed
print(f"Original shapes: tensorA =  {tensorA.shape}, tensorB = {tensorB.shape}")
print(f"Original shapes: tensorA =  {tensorA.shape}, tensorB.T = {tensorB.T.shape}")
print(f"Mutiplying {tensorA.shape} @ {tensorB.T.shape}  <- inner dimensions must match")
torch.matmul(tensorA, tensorB.T)

Original shapes: tensorA =  torch.Size([3, 2]), tensorB = torch.Size([3, 2])
Original shapes: tensorA =  torch.Size([3, 2]), tensorB.T = torch.Size([2, 3])
Mutiplying torch.Size([3, 2]) @ torch.Size([2, 3])  <- inner dimensions must match


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [44]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
# Find the min, max
print(torch.min(x), x.min())
print(torch.max(x), x.max())

tensor(0) tensor(0)
tensor(90) tensor(90)


In [46]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [47]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [48]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [49]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or size by size (hstack)
* Squeeze - removes all 1 dimensions to a target tensor
* unsqueeze - add a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way


In [50]:
# Let's create a tensor
import torch

x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [51]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [54]:
# Stach tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
# torch.squeeze - removes all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [56]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [57]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [58]:
# torch.permute - rearranges the dimension
x_original = torch.rand(size=(244, 244, 3))  # [height, width, color_channel]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0>1 1>2 2>0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([244, 244, 3])
New shape: torch.Size([3, 244, 244])


In [59]:
x_original[0, 0, 0] = 82123123
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(82123120.), tensor(82123120.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [60]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [61]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
x[0][0]

tensor([1, 2, 3])

In [63]:
x[0][0][0]

tensor(1)

In [64]:
x[0][2][2]

tensor(9)

In [65]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [66]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1:3]

tensor([[[2, 3],
         [5, 6],
         [8, 9]]])

In [67]:
# Index on x to return 9
print(x[0, 2, 2])
# index on x to return 3, 6, 9
print(x[0, :, 2])

tensor(9)
tensor([3, 6, 9])


## Pytorch tensors & Numpy
 Numpy is a popular scientific python numerical computing library.

 And because of this, PyTorch has functionality to interact with it.

 * Data in Numpy, want in PyTorch tensor  -> `torch.from_numpy(ndarray)`
 * PyTorch tensor-> NumPy -> `torch.Tensor.numpy()

In [68]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
# Change the value of array, what will this do to `tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [70]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [71]:
# Change the tensor, what happers to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network  learns:

`start with random number -> tensor operations -> update random numbers to try and make them of the data-> again -> again -> again`

To reduce the randomness in neural networks and PyTorch comes the concept of *random  seed*

In [72]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6036, 0.9978, 0.1648, 0.4420],
        [0.1054, 0.7395, 0.9827, 0.0374],
        [0.9027, 0.9235, 0.6702, 0.4644]])
tensor([[0.7402, 0.0919, 0.2689, 0.0428],
        [0.6995, 0.6100, 0.2413, 0.6827],
        [0.6160, 0.3850, 0.3314, 0.8314]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [73]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computation)

GPUs =  faster computation on numbers thanks to CUDA + Nvidia hardware + PyTorch working behin the scenes

### 1. Getting a GPU

1. Easiest -  Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchase
3. Use cloud computing - GCP, AWS, Azure allow to rent computers on the cloud

### 2. Check for GPU access with PyTorch

In [74]:
torch.cuda.is_available()

True

In [75]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [76]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors / models on the GPU is because using a GPU results in faster computations

In [77]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [78]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [79]:
# GPU to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])