# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(7, 7)
tensor_A, tensor_A.shape

(tensor([[0.0066, 0.3650, 0.5232, 0.2405, 0.1616, 0.9026, 0.4554],
         [0.0528, 0.9313, 0.0886, 0.2540, 0.5032, 0.7096, 0.3057],
         [0.7905, 0.7511, 0.7177, 0.4681, 0.8253, 0.3314, 0.3102],
         [0.3550, 0.9176, 0.5775, 0.3177, 0.7245, 0.8357, 0.2088],
         [0.9965, 0.7021, 0.9178, 0.4773, 0.1683, 0.4375, 0.1337],
         [0.0261, 0.2214, 0.2503, 0.5956, 0.3798, 0.2623, 0.7631],
         [0.1452, 0.1166, 0.8508, 0.1797, 0.2036, 0.0421, 0.3093]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_B = torch.rand(1, 7)

# Perform matrix multiplication
tensor_AB = torch.matmul(tensor_A, tensor_B.T)
tensor_AB, tensor_AB.shape

(tensor([[1.7850],
         [2.1517],
         [2.4227],
         [2.5970],
         [1.9381],
         [1.6410],
         [0.8695]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_C = torch.rand(7, 7)
tensor_D = torch.rand(1, 7)

# Matrix multiply tensors
tensor_CD = torch.matmul(tensor_C, tensor_D.T)
tensor_CD, tensor_CD.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3)
tensor_B = torch.rand(2, 3)
tensor_A_gpu = tensor_A.to(device)
tensor_B_gpu = tensor_B.to(device)

tensor_A_gpu, tensor_B_gpu

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
tensor_AB_gpu = torch.matmul(tensor_A_gpu, tensor_B_gpu.T)
tensor_AB_gpu, tensor_AB_gpu.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
max = torch.max(tensor_AB_gpu)
# Find min
min = torch.min(tensor_AB_gpu)

max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
argmax = torch.argmax(tensor_AB_gpu)

# Find arg min
argmin = torch.argmin(tensor_AB_gpu)

argmax, argmin

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)
print(tensor, tensor.shape)

# Remove single dimensions
tensor_squeezed = tensor.squeeze()

# Print out tensors and their shapes
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
